# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Email signal collector for the intelligence layer.

Gathers email signals from the Microsoft Graph API: unread counts by folder,
emails needing response, VIP sender detection, and send/receive volume.

The ``request`` callable is dependency-injected so this module has no direct
import of ``graph``, keeping it pure and unit-testable.
"""

from __future__ import annotations

import logging
from collections import Counter
from collections.abc import Callable
from datetime import datetime, timedelta
from typing import Any

from microsoft_mcp.intel._utils import parse_graph_datetime as _parse_dt
from microsoft_mcp.intel.types import (
    EmailNeedingResponse,
    EmailSignals,
    FolderUnreadCount,
    VipEmail,
)

logger = logging.getLogger(__name__)

# Minimum number of recent emails from a sender to qualify as VIP.
_VIP_THRESHOLD = 3

# Maximum messages to fetch per query.
_INBOX_PAGE_SIZE = 50
_SENT_PAGE_SIZE = 200


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _extract_sender(msg: dict[str, Any]) -> tuple[str, str]:
    """Extract (sender_name, sender_email) from a Graph message dict."""
    from_field = msg.get("from") or {}
    email_addr = from_field.get("emailAddress") or {}
    return (email_addr.get("name", ""), email_addr.get("address", ""))


def _fetch_folder_unread_counts(
    request: Callable[..., Any],
) -> list[FolderUnreadCount]:
    """Fetch unread and total counts for all mail folders."""
    data = request(
        "GET",
        "/me/mailFolders",
        params={
            "$top": 50,
            "$select": "displayName,unreadItemCount,totalItemCount",
        },
    )
    folders: list[FolderUnreadCount] = []
    for folder in data.get("value", []):
        folders.append(
            FolderUnreadCount(
                folder_name=folder.get("displayName", ""),
                unread_count=folder.get("unreadItemCount", 0),
                total_count=folder.get("totalItemCount", 0),
            )
        )
    return folders


def _fetch_inbox_messages(
    request: Callable[..., Any],
    since: datetime,
    *,
    unread_only: bool = True,
) -> list[dict[str, Any]]:
    """Fetch inbox messages received since ``since``.

    Args:
        request: Injected Graph request callable.
        since: Only return messages received after this UTC datetime.
        unread_only: If True, only fetch unread messages.

    Returns:
        List of raw Graph API message dicts.
    """
    since_iso = since.strftime("%Y-%m-%dT%H:%M:%SZ")
    if unread_only:
        filter_str = f"isRead eq false and receivedDateTime ge {since_iso}"
    else:
        filter_str = f"receivedDateTime ge {since_iso}"

    data = request(
        "GET",
        "/me/mailFolders/inbox/messages",
        params={
            "$filter": filter_str,
            "$orderby": "receivedDateTime desc",
            "$top": _INBOX_PAGE_SIZE,
            "$select": (
                "id,subject,from,receivedDateTime,isRead,"
                "importance,hasAttachments,bodyPreview"
            ),
        },
    )
    return data.get("value", [])


def _fetch_sent_count(
    request: Callable[..., Any],
    since: datetime,
) -> int:
    """Count messages sent in the given time window."""
    since_iso = since.strftime("%Y-%m-%dT%H:%M:%SZ")
    data = request(
        "GET",
        "/me/mailFolders/sentItems/messages",
        params={
            "$filter": f"sentDateTime ge {since_iso}",
            "$orderby": "sentDateTime desc",
            "$top": _SENT_PAGE_SIZE,
            "$select": "id",
            "$count": "true",
        },
    )
    # Prefer @odata.count if available, otherwise count returned items.
    return data.get("@odata.count", len(data.get("value", [])))


def _build_needs_response(
    messages: list[dict[str, Any]],
    now: datetime,
) -> list[EmailNeedingResponse]:
    """Build the list of emails needing a response from unread inbox messages."""
    result: list[EmailNeedingResponse] = []
    for msg in messages:
        sender_name, sender_email = _extract_sender(msg)
        received_str = msg.get("receivedDateTime", "")
        if not received_str:
            continue
        received_dt = _parse_dt(received_str)
        age_hours = (now - received_dt).total_seconds() / 3600.0
        result.append(
            EmailNeedingResponse(
                id=msg.get("id", ""),
                subject=msg.get("subject", ""),
                sender_name=sender_name,
                sender_email=sender_email,
                received_at=received_str,
                age_hours=round(age_hours, 2),
                importance=msg.get("importance", "normal"),
                has_attachments=msg.get("hasAttachments", False),
                body_preview=msg.get("bodyPreview", ""),
            )
        )
    return result


def _detect_vip_emails(
    messages: list[dict[str, Any]],
) -> list[VipEmail]:
    """Detect VIP senders (>= _VIP_THRESHOLD messages) and return their messages."""
    sender_counts: Counter[str] = Counter()
    for msg in messages:
        _, sender_email = _extract_sender(msg)
        if sender_email:
            sender_counts[sender_email.lower()] += 1

    vip_addresses = {
        addr for addr, count in sender_counts.items() if count >= _VIP_THRESHOLD
    }
    if not vip_addresses:
        return []

    result: list[VipEmail] = []
    for msg in messages:
        sender_name, sender_email = _extract_sender(msg)
        normalized = sender_email.lower()
        if normalized not in vip_addresses:
            continue
        result.append(
            VipEmail(
                id=msg.get("id", ""),
                subject=msg.get("subject", ""),
                sender_name=sender_name,
                sender_email=sender_email,
                received_at=msg.get("receivedDateTime", ""),
                is_read=msg.get("isRead", False),
                importance=msg.get("importance", "normal"),
                interaction_count=sender_counts[normalized],
            )
        )
    return result


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def collect_email_signals(
    request: Callable[..., Any],
    *,
    now: datetime,
    lookback_hours: int = 24,
) -> EmailSignals:
    """Collect email intelligence signals.

    Args:
        request: Injected Graph request callable — signature
            ``request(method, path, *, params=None, json=None) -> dict``.
        now: Current UTC datetime (injected for deterministic testing; never
            call ``datetime.now()`` inside this function).
        lookback_hours: Look-back window in hours (default 24).

    Returns:
        :class:`EmailSignals` with unread counts, response-needed emails,
        VIP emails, and send/receive volume.
    """
    since = now - timedelta(hours=lookback_hours)

    logger.debug("Fetching folder unread counts")
    folder_counts = _fetch_folder_unread_counts(request)
    unread_total = sum(f["unread_count"] for f in folder_counts)

    logger.debug("Fetching unread inbox messages (lookback %d h)", lookback_hours)
    unread_messages = _fetch_inbox_messages(request, since, unread_only=True)
    needs_response = _build_needs_response(unread_messages, now)

    logger.debug("Fetching all inbox messages for VIP detection")
    all_inbox = _fetch_inbox_messages(request, since, unread_only=False)
    vip_unread = _detect_vip_emails(all_inbox)

    logger.debug("Fetching sent message count")
    sent_count = _fetch_sent_count(request, since)

    return EmailSignals(
        unread_total=unread_total,
        unread_by_folder=folder_counts,
        needs_response=needs_response,
        vip_unread=vip_unread,
        received_last_24h=len(all_inbox),
        sent_last_24h=sent_count,
    )
