# Generated by OrchestKit Claude Plugin
# Created: 2026-06-16

import json
from microsoft_mcp import auth_msal

TEST_EMAIL = "broach@cresa.com"


def _auth(tmp_path, api_type):
    return auth_msal.MSALRefreshTokenAuth(
        tokens_dir=tmp_path,
        client_id="d3590ed6-52b3-4102-aeff-aad2292ab01c",
        tenant_id="common",
        account_identifier=TEST_EMAIL,
        api_type=api_type,
    )


def test_graph_paths_unchanged(tmp_path):
    a = _auth(tmp_path, "graph")
    assert a._access_token_json_path().name == f"{TEST_EMAIL}_access_token.json"
    assert a._access_token_raw_path().name == f"{TEST_EMAIL}_access_only.txt"
    assert a._refresh_token_path().name == f"{TEST_EMAIL}_refresh_only.txt"


def test_outlook_paths_use_outlook_suffix(tmp_path):
    a = _auth(tmp_path, "outlook")
    assert a._access_token_json_path().name == f"{TEST_EMAIL}_outlook_access_token.json"
    assert a._access_token_raw_path().name == f"{TEST_EMAIL}_outlook_access_only.txt"
    assert a._refresh_token_path().name == f"{TEST_EMAIL}_refresh_only.txt"


def test_save_records_api_type(tmp_path):
    a = _auth(tmp_path, "outlook")
    a._save_tokens("tok", "refresh", 3600, auth_msal.OUTLOOK_SCOPE, email=TEST_EMAIL)
    data = json.loads(a._access_token_json_path().read_text())
    assert data["api_type"] == "outlook"


def test_default_scope_selection(tmp_path):
    g = _auth(tmp_path, "graph")
    o = _auth(tmp_path, "outlook")
    assert g._default_scope() == auth_msal.GRAPH_SCOPE
    assert o._default_scope() == auth_msal.OUTLOOK_SCOPE


def test_api_type_defaults_to_graph(tmp_path):
    a = auth_msal.MSALRefreshTokenAuth(
        tokens_dir=tmp_path, account_identifier=TEST_EMAIL
    )
    assert a.api_type == "graph"
    assert a._access_token_json_path().name == f"{TEST_EMAIL}_access_token.json"
