# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Tests for parse_email_signature and normalize_phone_number MCP tools.

Tools delegate entirely to signature_parser — no Graph calls needed.
"""

from src.microsoft_mcp import tools


# ---------------------------------------------------------------------------
# parse_email_signature
# ---------------------------------------------------------------------------

SAMPLE_BODY = """\
Hi, I am out of office until Monday.

For urgent matters please contact Jane Doe - Director: jane.doe@acmecorp.com

---
John Smith
VP of Sales
Acme Corp
M: (949) 462-4106
john.smith@acmecorp.com
"""


class TestParseEmailSignature:
    def test_returns_contacts_and_job_changes(self):
        result = tools.parse_email_signature.fn(SAMPLE_BODY)
        assert "contacts" in result
        assert "job_changes" in result

    def test_contacts_is_list(self):
        result = tools.parse_email_signature.fn(SAMPLE_BODY)
        assert isinstance(result["contacts"], list)

    def test_html_path(self):
        html_body = "<p>Hello</p><hr/><div>Jane Smith<br/>CEO<br/>jane@corp.com</div>"
        result = tools.parse_email_signature.fn(html_body, is_html=True)
        assert "contacts" in result
        assert "job_changes" in result

    def test_extract_alternatives_false(self):
        result = tools.parse_email_signature.fn(SAMPLE_BODY, extract_alternatives=False)
        assert "contacts" in result


# ---------------------------------------------------------------------------
# normalize_phone_number
# ---------------------------------------------------------------------------


class TestNormalizePhoneNumber:
    def test_us_formatted(self):
        assert tools.normalize_phone_number.fn("(949) 462-4106") == "+19494624106"

    def test_default_region_us(self):
        assert (
            tools.normalize_phone_number.fn("(949) 462-4106", region="US")
            == "+19494624106"
        )

    def test_junk_returns_empty(self):
        assert tools.normalize_phone_number.fn("junk") == ""

    def test_already_e164(self):
        assert tools.normalize_phone_number.fn("+19494624106") == "+19494624106"
