# Generated by OrchestKit Claude Plugin
# Created: 2026-06-16

"""Tests for reply_email_draft, reply_all_email_draft, and forward_email_draft.

These tools must NEVER send mail — they only create drafts via Graph's
draft-creating actions (createReply / createReplyAll / createForward) and
optionally PATCH the body/recipients.
"""

from unittest.mock import call, patch

import pytest


# ---------------------------------------------------------------------------
# Shared fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(autouse=True)
def _clear_signature_env(monkeypatch):
    """Suppress any env-default signatures so tests get predictable bodies."""
    for var in (
        "MICROSOFT_MCP_DEFAULT_SIGNATURE",
        "MICROSOFT_MCP_REPLY_SIGNATURE",
        "MICROSOFT_MCP_SIGNATURE_ACCOUNT",
        "MICROSOFT_MCP_SIGNATURES_DIR",
    ):
        monkeypatch.setenv(var, "")


def _draft_message(draft_id: str, **overrides):
    draft = {
        "id": draft_id,
        "subject": "Re: Test subject",
        "from": {"emailAddress": {"name": "Me", "address": "me@example.com"}},
        "toRecipients": [{"emailAddress": {"address": "alice@example.com"}}],
        "ccRecipients": [],
        "bccRecipients": [],
        "body": {"contentType": "html", "content": "<p>Original quote</p>"},
        "bodyPreview": "Original quote",
        "conversationId": f"conv-{draft_id}",
        "webLink": f"https://outlook.office.com/mail/deeplink/compose/{draft_id}",
        "createdDateTime": "2026-06-01T10:00:00Z",
        "lastModifiedDateTime": "2026-06-01T10:01:00Z",
        "isDraft": True,
        "isRead": True,
    }
    draft.update(overrides)
    return draft


# ---------------------------------------------------------------------------
# reply_email_draft
# ---------------------------------------------------------------------------


@patch("src.microsoft_mcp.tools.graph")
def test_reply_email_draft_posts_create_reply(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.return_value = _draft_message("d-reply-1")

    result = tools.reply_email_draft.fn(email_id="msg-1")

    mock_graph.request.assert_called_once_with("POST", "/me/messages/msg-1/createReply")
    assert result["status"] == "draft_created"
    assert result["draft_id"] == "d-reply-1"
    assert result["draft"]["is_draft"] is True


@patch("src.microsoft_mcp.tools.graph")
def test_reply_email_draft_patches_body_when_provided(mock_graph):
    from src.microsoft_mcp import tools

    body_text = "<p>Thanks!</p>"
    mock_graph.request.side_effect = [
        _draft_message("d-reply-2"),
        _draft_message("d-reply-2", body={"contentType": "HTML", "content": body_text}),
    ]

    result = tools.reply_email_draft.fn(email_id="msg-2", body=body_text)

    assert mock_graph.request.call_args_list == [
        call("POST", "/me/messages/msg-2/createReply"),
        call(
            "PATCH",
            "/me/messages/d-reply-2",
            json={"body": {"contentType": "HTML", "content": body_text}},
        ),
    ]
    assert result["draft_id"] == "d-reply-2"


@patch("src.microsoft_mcp.tools.graph")
def test_reply_email_draft_no_patch_when_no_body(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.return_value = _draft_message("d-reply-3")

    tools.reply_email_draft.fn(email_id="msg-3")

    # Only the createReply POST — no PATCH
    mock_graph.request.assert_called_once_with("POST", "/me/messages/msg-3/createReply")


@patch("src.microsoft_mcp.tools.graph")
def test_reply_email_draft_never_calls_send(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.side_effect = [
        _draft_message("d-reply-4"),
        _draft_message("d-reply-4", body={"contentType": "HTML", "content": "Hi"}),
    ]

    tools.reply_email_draft.fn(email_id="msg-4", body="Hi")

    for c in mock_graph.request.call_args_list:
        path = c.args[1] if len(c.args) > 1 else c.kwargs.get("path", "")
        assert not path.endswith("/send"), f"Unexpected /send call: {c}"


@patch("src.microsoft_mcp.tools.graph")
def test_reply_email_draft_assistant_profile(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.return_value = _draft_message(
        "d-reply-5",
        webLink="https://outlook.office.com/mail/deeplink/compose/d-reply-5",
    )

    result = tools.reply_email_draft.fn(email_id="msg-5", response_profile="assistant")

    assert result["draft"]["id"] == "d-reply-5"
    assert "web_link" in result["draft"]
    assert result["draft"]["is_draft"] is True


# ---------------------------------------------------------------------------
# reply_all_email_draft
# ---------------------------------------------------------------------------


@patch("src.microsoft_mcp.tools.graph")
def test_reply_all_email_draft_posts_create_reply_all(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.return_value = _draft_message(
        "d-replyall-1",
        toRecipients=[
            {"emailAddress": {"address": "alice@example.com"}},
            {"emailAddress": {"address": "bob@example.com"}},
        ],
    )

    result = tools.reply_all_email_draft.fn(email_id="msg-10")

    mock_graph.request.assert_called_once_with(
        "POST", "/me/messages/msg-10/createReplyAll"
    )
    assert result["status"] == "draft_created"
    assert result["draft_id"] == "d-replyall-1"
    assert result["draft"]["is_draft"] is True


@patch("src.microsoft_mcp.tools.graph")
def test_reply_all_email_draft_patches_body_when_provided(mock_graph):
    from src.microsoft_mcp import tools

    body_text = "<p>Reply all body</p>"
    mock_graph.request.side_effect = [
        _draft_message("d-replyall-2"),
        _draft_message(
            "d-replyall-2", body={"contentType": "HTML", "content": body_text}
        ),
    ]

    result = tools.reply_all_email_draft.fn(email_id="msg-11", body=body_text)

    assert mock_graph.request.call_args_list == [
        call("POST", "/me/messages/msg-11/createReplyAll"),
        call(
            "PATCH",
            "/me/messages/d-replyall-2",
            json={"body": {"contentType": "HTML", "content": body_text}},
        ),
    ]
    assert result["draft_id"] == "d-replyall-2"


@patch("src.microsoft_mcp.tools.graph")
def test_reply_all_email_draft_never_calls_send(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.side_effect = [
        _draft_message("d-replyall-3"),
        _draft_message(
            "d-replyall-3", body={"contentType": "HTML", "content": "Team update"}
        ),
    ]

    tools.reply_all_email_draft.fn(email_id="msg-12", body="Team update")

    for c in mock_graph.request.call_args_list:
        path = c.args[1] if len(c.args) > 1 else c.kwargs.get("path", "")
        assert not path.endswith("/send"), f"Unexpected /send call: {c}"


# ---------------------------------------------------------------------------
# forward_email_draft
# ---------------------------------------------------------------------------


@patch("src.microsoft_mcp.tools.graph")
def test_forward_email_draft_posts_create_forward_and_patches(mock_graph):
    from src.microsoft_mcp import tools

    comment = "<p>FYI</p>"
    patched = _draft_message(
        "d-fwd-1",
        toRecipients=[{"emailAddress": {"address": "carol@example.com"}}],
        body={"contentType": "HTML", "content": comment},
    )
    mock_graph.request.side_effect = [
        _draft_message("d-fwd-1"),
        patched,
    ]

    result = tools.forward_email_draft.fn(
        email_id="msg-20",
        to=["carol@example.com"],
        comment=comment,
    )

    expected_patch_payload = {
        "toRecipients": [{"emailAddress": {"address": "carol@example.com"}}],
        "body": {"contentType": "HTML", "content": comment},
    }
    assert mock_graph.request.call_args_list == [
        call("POST", "/me/messages/msg-20/createForward"),
        call("PATCH", "/me/messages/d-fwd-1", json=expected_patch_payload),
    ]
    assert result["status"] == "draft_created"
    assert result["draft_id"] == "d-fwd-1"
    assert result["draft"]["is_draft"] is True


@patch("src.microsoft_mcp.tools.graph")
def test_forward_email_draft_patches_recipients_only_when_no_comment(mock_graph):
    from src.microsoft_mcp import tools

    patched = _draft_message(
        "d-fwd-2",
        toRecipients=[
            {"emailAddress": {"address": "dave@example.com"}},
            {"emailAddress": {"address": "eve@example.com"}},
        ],
    )
    mock_graph.request.side_effect = [
        _draft_message("d-fwd-2"),
        patched,
    ]

    result = tools.forward_email_draft.fn(
        email_id="msg-21",
        to=["dave@example.com", "eve@example.com"],
    )

    expected_patch_payload = {
        "toRecipients": [
            {"emailAddress": {"address": "dave@example.com"}},
            {"emailAddress": {"address": "eve@example.com"}},
        ],
    }
    assert mock_graph.request.call_args_list == [
        call("POST", "/me/messages/msg-21/createForward"),
        call("PATCH", "/me/messages/d-fwd-2", json=expected_patch_payload),
    ]
    assert result["draft_id"] == "d-fwd-2"


@patch("src.microsoft_mcp.tools.graph")
def test_forward_email_draft_raises_on_empty_to(mock_graph):
    from src.microsoft_mcp import tools

    with pytest.raises(ValueError, match="to"):
        tools.forward_email_draft.fn(email_id="msg-22", to=[])


@patch("src.microsoft_mcp.tools.graph")
def test_forward_email_draft_never_calls_send(mock_graph):
    from src.microsoft_mcp import tools

    comment = "See below"
    mock_graph.request.side_effect = [
        _draft_message("d-fwd-3"),
        _draft_message(
            "d-fwd-3",
            toRecipients=[{"emailAddress": {"address": "frank@example.com"}}],
            body={"contentType": "HTML", "content": comment},
        ),
    ]

    tools.forward_email_draft.fn(
        email_id="msg-23",
        to=["frank@example.com"],
        comment=comment,
    )

    for c in mock_graph.request.call_args_list:
        path = c.args[1] if len(c.args) > 1 else c.kwargs.get("path", "")
        assert not path.endswith("/send"), f"Unexpected /send call: {c}"


@patch("src.microsoft_mcp.tools.graph")
def test_forward_email_draft_assistant_profile(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.side_effect = [
        _draft_message("d-fwd-4"),
        _draft_message(
            "d-fwd-4",
            toRecipients=[{"emailAddress": {"address": "grace@example.com"}}],
        ),
    ]

    result = tools.forward_email_draft.fn(
        email_id="msg-24",
        to=["grace@example.com"],
        response_profile="assistant",
    )

    assert result["draft"]["id"] == "d-fwd-4"
    assert "web_link" in result["draft"]
    assert result["draft"]["is_draft"] is True


# ---------------------------------------------------------------------------
# send_email_draft
# ---------------------------------------------------------------------------


@patch("src.microsoft_mcp.tools.graph")
def test_send_email_draft_posts_to_send_endpoint(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.return_value = None  # Graph returns 202 No Content

    tools.send_email_draft.fn(draft_id="d-send-1")

    mock_graph.request.assert_called_once()
    call_args = mock_graph.request.call_args
    method = call_args.args[0]
    path = call_args.args[1]
    assert method == "POST"
    assert path.endswith("/d-send-1/send")


@patch("src.microsoft_mcp.tools.graph")
def test_send_email_draft_returns_sent_shape(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.return_value = None

    result = tools.send_email_draft.fn(draft_id="d-send-2")

    assert result == {"status": "sent", "draft_id": "d-send-2"}


@patch("src.microsoft_mcp.tools.graph")
def test_send_email_draft_reraises_on_error(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.side_effect = RuntimeError("Graph 500")

    with pytest.raises(RuntimeError, match="Graph 500"):
        tools.send_email_draft.fn(draft_id="d-send-3")
