# Generated by OrchestKit Claude Plugin
# Created: 2026-06-16


import datetime as dt
import json as _json

import pytest

from microsoft_mcp import auth_cli

TEST_EMAIL = "broach@cresa.com"


def test_format_expiry_converts_stored_zulu_to_utc_human():
    assert auth_cli._format_expiry("2026-06-15T21:25:06Z") == "2026-06-15 21:25:06 UTC"


def test_format_expiry_handles_none_and_garbage():
    assert auth_cli._format_expiry(None) == "unknown"
    assert auth_cli._format_expiry("not-a-date") == "not-a-date"


def test_color_disabled_when_no_color_env(monkeypatch):
    monkeypatch.setenv("NO_COLOR", "1")
    assert auth_cli._color_enabled() is False
    assert auth_cli._c("x", "green") == "x"  # no escape codes


def test_color_disabled_for_non_tty(monkeypatch):
    monkeypatch.delenv("NO_COLOR", raising=False)
    monkeypatch.delenv("MICROSOFT_MCP_FORCE_COLOR", raising=False)

    class _NotATty:
        def isatty(self):
            return False

    assert auth_cli._color_enabled(_NotATty()) is False


def test_color_forced_on(monkeypatch):
    monkeypatch.delenv("NO_COLOR", raising=False)
    monkeypatch.setenv("MICROSOFT_MCP_FORCE_COLOR", "1")
    assert auth_cli._color_enabled() is True
    assert auth_cli._c("ok", "green") == "\033[32mok\033[0m"


def _write_graph_token(tmp_path, identifier, expires_delta_seconds=3600):
    now = dt.datetime.now(dt.timezone.utc)
    expires = now + dt.timedelta(seconds=expires_delta_seconds)
    payload = {
        "email": identifier,
        "access_token": "header.eyJ1cG4iOiJ4In0.sig",
        "token_type": "Bearer",
        "expires_in": expires_delta_seconds,
        "expires_at": expires.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "refreshed_at": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "scopes": "https://graph.microsoft.com/.default offline_access",
        "api_type": "graph",
    }
    (tmp_path / f"{identifier}_access_token.json").write_text(_json.dumps(payload))
    (tmp_path / f"{identifier}_refresh_only.txt").write_text("fake-refresh-token")
    return payload


def _msal_env(monkeypatch, tmp_path):
    monkeypatch.setenv("MICROSOFT_MCP_AUTH_METHOD", "msal")
    monkeypatch.setenv("MICROSOFT_MCP_TOKENS_DIR", str(tmp_path))
    monkeypatch.setenv(
        "MICROSOFT_MCP_CLIENT_ID", "d3590ed6-52b3-4102-aeff-aad2292ab01c"
    )
    monkeypatch.delenv("MICROSOFT_MCP_TENANT_ID", raising=False)


def test_refresh_all_prints_per_account_status(monkeypatch, tmp_path, capsys):
    _msal_env(monkeypatch, tmp_path)
    _write_graph_token(tmp_path, TEST_EMAIL)
    rc = auth_cli.main(["refresh"])
    out = capsys.readouterr().out
    assert rc == 0
    assert TEST_EMAIL in out
    assert "Graph: Valid, expires" in out
    assert "UTC" in out


def test_refresh_requires_msal(monkeypatch, tmp_path):
    monkeypatch.setenv("MICROSOFT_MCP_AUTH_METHOD", "azure")
    with pytest.raises(SystemExit) as exc:
        auth_cli.main(["refresh"])
    assert exc.value.code == 2


def test_refresh_json_output(monkeypatch, tmp_path, capsys):
    _msal_env(monkeypatch, tmp_path)
    _write_graph_token(tmp_path, TEST_EMAIL)
    rc = auth_cli.main(["refresh", "--json"])
    out = capsys.readouterr().out
    assert rc == 0
    parsed = _json.loads(out)
    assert parsed[0]["identifier"] == TEST_EMAIL
    assert parsed[0]["status"] == "valid"


def test_list_accounts_human(monkeypatch, tmp_path, capsys):
    _msal_env(monkeypatch, tmp_path)
    _write_graph_token(tmp_path, TEST_EMAIL)
    rc = auth_cli.main(["list"])
    out = capsys.readouterr().out
    assert rc == 0
    assert TEST_EMAIL in out
