# Generated by OrchestKit Claude Plugin
# Created: 2026-06-16

"""Tests for Microsoft To-Do list + task CRUD tools."""

from unittest.mock import patch

from src.microsoft_mcp import tools

# ---------------------------------------------------------------------------
# list_todo_lists
# ---------------------------------------------------------------------------

_LISTS_RESPONSE = [
    {"id": "list1", "displayName": "Tasks", "isOwner": True},
    {"id": "list2", "displayName": "Work", "isOwner": True},
]


@patch("src.microsoft_mcp.tools.graph.request_paginated")
def test_list_todo_lists(mock_paged):
    mock_paged.return_value = iter(_LISTS_RESPONSE)
    result = tools.list_todo_lists.fn()
    call_path = mock_paged.call_args[0][0]
    assert call_path == "/me/todo/lists"
    assert len(result) == 2
    assert result[0]["id"] == "list1"
    assert result[1]["displayName"] == "Work"


# ---------------------------------------------------------------------------
# create_todo_list
# ---------------------------------------------------------------------------


@patch("src.microsoft_mcp.tools.graph.request")
def test_create_todo_list(mock_req):
    mock_req.return_value = {"id": "list99", "displayName": "My New List"}
    result = tools.create_todo_list.fn(name="My New List")
    args, kwargs = mock_req.call_args
    assert args[0] == "POST"
    assert args[1] == "/me/todo/lists"
    assert kwargs["json"] == {"displayName": "My New List"}
    assert result["id"] == "list99"
    assert result["displayName"] == "My New List"


# ---------------------------------------------------------------------------
# list_tasks
# ---------------------------------------------------------------------------

_TASKS_RESPONSE = [
    {
        "id": "task1",
        "title": "Buy milk",
        "status": "notStarted",
        "importance": "normal",
    },
    {
        "id": "task2",
        "title": "Call dentist",
        "status": "completed",
        "importance": "high",
    },
]


@patch("src.microsoft_mcp.tools.graph.request_paginated")
@patch("src.microsoft_mcp.tools.graph.request")
def test_list_tasks(mock_req, mock_paged):
    mock_req.return_value = _LISTS_RESPONSE  # for /me/todo/lists
    mock_paged.side_effect = [
        iter(_LISTS_RESPONSE),  # _resolve_todo_list call
        iter(_TASKS_RESPONSE),  # list_tasks call
    ]
    result = tools.list_tasks.fn(list_name="Tasks")
    assert len(result) == 2
    assert result[0]["id"] == "task1"


@patch("src.microsoft_mcp.tools.graph.request_paginated")
def test_list_tasks_status_filter(mock_paged):
    mock_paged.side_effect = [
        iter(_LISTS_RESPONSE),  # _resolve_todo_list call
        iter([_TASKS_RESPONSE[0]]),  # filtered list_tasks call
    ]
    tools.list_tasks.fn(list_name="Tasks", status="notStarted")
    # Second paginated call should include $filter param
    second_call = mock_paged.call_args_list[1]
    (
        second_call[1].get("params") or second_call[0][1]
        if len(second_call[0]) > 1
        else second_call[1].get("params", {})
    )
    # Check the $filter is in the params
    all_calls = mock_paged.call_args_list
    last_call_kwargs = all_calls[-1][1] if all_calls[-1][1] else {}
    last_call_args = all_calls[-1][0]
    # extract params from either positional or keyword
    if "params" in last_call_kwargs:
        task_params = last_call_kwargs["params"]
    elif len(last_call_args) > 1:
        task_params = last_call_args[1]
    else:
        task_params = {}
    assert "$filter" in task_params
    assert "notStarted" in task_params["$filter"]


# ---------------------------------------------------------------------------
# create_task
# ---------------------------------------------------------------------------


@patch("src.microsoft_mcp.tools.graph.request")
@patch("src.microsoft_mcp.tools.graph.request_paginated")
def test_create_task(mock_paged, mock_req):
    mock_paged.return_value = iter(_LISTS_RESPONSE)
    mock_req.return_value = {
        "id": "new_task_1",
        "title": "Write docs",
        "status": "notStarted",
        "importance": "normal",
    }
    result = tools.create_task.fn(list_name="Tasks", title="Write docs")
    # Verify POST was called to the right path
    post_call = [c for c in mock_req.call_args_list if c[0][0] == "POST"]
    assert post_call, "Expected a POST call"
    args = post_call[0][0]
    assert "/me/todo/lists/list1/tasks" in args[1]
    (
        post_call[0][1]["json"] if post_call[0][1].get("json") else post_call[0][1]
    )
    assert result["id"] == "new_task_1"


@patch("src.microsoft_mcp.tools.graph.request")
@patch("src.microsoft_mcp.tools.graph.request_paginated")
def test_create_task_with_due(mock_paged, mock_req):
    mock_paged.return_value = iter(_LISTS_RESPONSE)
    mock_req.return_value = {
        "id": "new_task_2",
        "title": "Submit report",
        "status": "notStarted",
        "dueDateTime": {"dateTime": "2026-06-19T23:59:00", "timeZone": "UTC"},
    }
    result = tools.create_task.fn(list_name="Tasks", title="Submit report", due="+3d")
    post_call = [c for c in mock_req.call_args_list if c[0][0] == "POST"]
    assert post_call
    payload = post_call[0][1].get("json", {})
    assert "dueDateTime" in payload
    assert result["id"] == "new_task_2"


@patch("src.microsoft_mcp.tools.graph.request")
@patch("src.microsoft_mcp.tools.graph.request_paginated")
def test_create_task_auto_creates_missing_list(mock_paged, mock_req):
    # First paginated call returns empty (list not found)
    # Then request POST creates the list, then POST creates the task
    mock_paged.return_value = iter([])  # no existing lists
    mock_req.side_effect = [
        {"id": "new_list_id", "displayName": "Shopping"},  # list creation
        {
            "id": "new_task_3",
            "title": "Buy apples",
            "status": "notStarted",
        },  # task creation
    ]
    result = tools.create_task.fn(list_name="Shopping", title="Buy apples")
    assert result["id"] == "new_task_3"
    # First request call should be POST to /me/todo/lists
    list_create_call = mock_req.call_args_list[0]
    assert list_create_call[0][0] == "POST"
    assert list_create_call[0][1] == "/me/todo/lists"


# ---------------------------------------------------------------------------
# update_task
# ---------------------------------------------------------------------------


@patch("src.microsoft_mcp.tools.graph.request")
@patch("src.microsoft_mcp.tools.graph.request_paginated")
def test_update_task(mock_paged, mock_req):
    mock_paged.return_value = iter(_LISTS_RESPONSE)
    mock_req.return_value = {
        "id": "task1",
        "title": "Buy oat milk",
        "status": "notStarted",
        "importance": "high",
    }
    result = tools.update_task.fn(
        list_name="Tasks",
        task_id="task1",
        title="Buy oat milk",
        importance="high",
    )
    patch_call = [c for c in mock_req.call_args_list if c[0][0] == "PATCH"]
    assert patch_call
    args = patch_call[0][0]
    assert "task1" in args[1]
    payload = patch_call[0][1].get("json", {})
    assert payload.get("title") == "Buy oat milk"
    assert payload.get("importance") == "high"
    assert result["id"] == "task1"


# ---------------------------------------------------------------------------
# complete_task
# ---------------------------------------------------------------------------


@patch("src.microsoft_mcp.tools.graph.request")
@patch("src.microsoft_mcp.tools.graph.request_paginated")
def test_complete_task(mock_paged, mock_req):
    mock_paged.return_value = iter(_LISTS_RESPONSE)
    mock_req.return_value = {"id": "task1", "status": "completed"}
    result = tools.complete_task.fn(list_name="Tasks", task_id="task1")
    patch_call = [c for c in mock_req.call_args_list if c[0][0] == "PATCH"]
    assert patch_call
    args = patch_call[0][0]
    assert "task1" in args[1]
    payload = patch_call[0][1].get("json", {})
    assert payload == {"status": "completed"}
    assert result["status"] == "completed"


# ---------------------------------------------------------------------------
# delete_task
# ---------------------------------------------------------------------------


@patch("src.microsoft_mcp.tools.graph.request")
@patch("src.microsoft_mcp.tools.graph.request_paginated")
def test_delete_task(mock_paged, mock_req):
    mock_paged.return_value = iter(_LISTS_RESPONSE)
    mock_req.return_value = None
    result = tools.delete_task.fn(list_name="Tasks", task_id="task1")
    delete_call = [c for c in mock_req.call_args_list if c[0][0] == "DELETE"]
    assert delete_call
    args = delete_call[0][0]
    assert "task1" in args[1]
    assert result == {"status": "deleted", "task_id": "task1"}
