# Generated by OrchestKit Claude Plugin
# Created: 2026-06-16

from microsoft_mcp import auth_cli

TEST_EMAIL = "broach@cresa.com"


def test_format_expiry_converts_stored_zulu_to_utc_human():
    assert auth_cli._format_expiry("2026-06-15T21:25:06Z") == "2026-06-15 21:25:06 UTC"


def test_format_expiry_handles_none_and_garbage():
    assert auth_cli._format_expiry(None) == "unknown"
    assert auth_cli._format_expiry("not-a-date") == "not-a-date"


def test_color_disabled_when_no_color_env(monkeypatch):
    monkeypatch.setenv("NO_COLOR", "1")
    assert auth_cli._color_enabled() is False
    assert auth_cli._c("x", "green") == "x"  # no escape codes


def test_color_disabled_for_non_tty(monkeypatch):
    monkeypatch.delenv("NO_COLOR", raising=False)
    monkeypatch.delenv("MICROSOFT_MCP_FORCE_COLOR", raising=False)

    class _NotATty:
        def isatty(self):
            return False

    assert auth_cli._color_enabled(_NotATty()) is False


def test_color_forced_on(monkeypatch):
    monkeypatch.delenv("NO_COLOR", raising=False)
    monkeypatch.setenv("MICROSOFT_MCP_FORCE_COLOR", "1")
    assert auth_cli._color_enabled() is True
    assert auth_cli._c("ok", "green") == "\033[32mok\033[0m"
