# Generated by OrchestKit Claude Plugin
# Created: 2026-06-16

"""Tests for get_mailtips tool.

Covers: POST path, body shape, tip flattening, HTML stripping on auto_reply,
ValueError on empty emails list.
"""

from unittest.mock import patch

import pytest


def _raw_tip(
    address: str = "alice@example.com",
    auto_reply_html: str | None = None,
    mailbox_full: bool = False,
    max_message_size: int | None = 36700160,
    recipient_scope: str | None = "organization",
    delivery_restricted: bool = False,
) -> dict:
    tip: dict = {
        "emailAddress": {"name": "Alice", "address": address},
        "automaticReplies": {},
        "mailboxFull": mailbox_full,
        "maxMessageSize": max_message_size,
        "recipientScope": recipient_scope,
        "deliveryRestriction": {"isDeliveryRestricted": delivery_restricted},
    }
    if auto_reply_html is not None:
        tip["automaticReplies"]["message"] = auto_reply_html
    return tip


# ---------------------------------------------------------------------------
# POST path and body
# ---------------------------------------------------------------------------


@patch("src.microsoft_mcp.tools.graph")
def test_get_mailtips_posts_correct_path(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.return_value = {"value": [_raw_tip()]}

    tools.get_mailtips.fn(emails=["alice@example.com"])

    call_args = mock_graph.request.call_args
    assert call_args.args[0] == "POST"
    assert call_args.args[1] == "/me/getMailTips"


@patch("src.microsoft_mcp.tools.graph")
def test_get_mailtips_body_has_email_addresses(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.return_value = {"value": [_raw_tip()]}

    tools.get_mailtips.fn(emails=["alice@example.com", "bob@example.com"])

    body = mock_graph.request.call_args.kwargs["json"]
    assert body["EmailAddresses"] == ["alice@example.com", "bob@example.com"]


@patch("src.microsoft_mcp.tools.graph")
def test_get_mailtips_body_has_default_options(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.return_value = {"value": [_raw_tip()]}

    tools.get_mailtips.fn(emails=["alice@example.com"])

    body = mock_graph.request.call_args.kwargs["json"]
    options_str = body["MailTipsOptions"]
    for opt in [
        "automaticReplies",
        "mailboxFullStatus",
        "maxMessageSize",
        "recipientScope",
        "deliveryRestriction",
    ]:
        assert opt in options_str


@patch("src.microsoft_mcp.tools.graph")
def test_get_mailtips_custom_options_joined(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.return_value = {"value": [_raw_tip()]}

    tools.get_mailtips.fn(
        emails=["alice@example.com"],
        options=["automaticReplies", "mailboxFullStatus"],
    )

    body = mock_graph.request.call_args.kwargs["json"]
    assert body["MailTipsOptions"] == "automaticReplies,mailboxFullStatus"


# ---------------------------------------------------------------------------
# Tip flattening / shape
# ---------------------------------------------------------------------------


@patch("src.microsoft_mcp.tools.graph")
def test_get_mailtips_flattens_tip_shape(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.return_value = {
        "value": [
            _raw_tip(
                address="alice@example.com",
                auto_reply_html=None,
                mailbox_full=False,
                max_message_size=36700160,
                recipient_scope="organization",
                delivery_restricted=False,
            )
        ]
    }

    result = tools.get_mailtips.fn(emails=["alice@example.com"])

    assert len(result) == 1
    tip = result[0]
    assert tip["email"] == "alice@example.com"
    assert tip["auto_reply"] is None
    assert tip["mailbox_full"] is False
    assert tip["max_message_size_bytes"] == 36700160
    assert tip["recipient_scope"] == "organization"
    assert tip["delivery_restricted"] is False


@patch("src.microsoft_mcp.tools.graph")
def test_get_mailtips_strips_html_from_auto_reply(mock_graph):
    from src.microsoft_mcp import tools

    html_reply = "<p>I am <b>out of office</b> until Monday.</p>"
    mock_graph.request.return_value = {
        "value": [_raw_tip(address="bob@example.com", auto_reply_html=html_reply)]
    }

    result = tools.get_mailtips.fn(emails=["bob@example.com"])

    tip = result[0]
    assert "<" not in tip["auto_reply"]
    assert "out of office" in tip["auto_reply"]
    assert "Monday" in tip["auto_reply"]


@patch("src.microsoft_mcp.tools.graph")
def test_get_mailtips_auto_reply_none_when_no_message(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.return_value = {"value": [_raw_tip(auto_reply_html=None)]}

    result = tools.get_mailtips.fn(emails=["carol@example.com"])

    assert result[0]["auto_reply"] is None


@patch("src.microsoft_mcp.tools.graph")
def test_get_mailtips_mailbox_full_true(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.return_value = {
        "value": [_raw_tip(address="full@example.com", mailbox_full=True)]
    }

    result = tools.get_mailtips.fn(emails=["full@example.com"])

    assert result[0]["mailbox_full"] is True


@patch("src.microsoft_mcp.tools.graph")
def test_get_mailtips_delivery_restricted_true(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.return_value = {
        "value": [_raw_tip(address="restricted@example.com", delivery_restricted=True)]
    }

    result = tools.get_mailtips.fn(emails=["restricted@example.com"])

    assert result[0]["delivery_restricted"] is True


@patch("src.microsoft_mcp.tools.graph")
def test_get_mailtips_multiple_recipients(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.return_value = {
        "value": [
            _raw_tip(address="alice@example.com"),
            _raw_tip(address="bob@example.com", mailbox_full=True),
        ]
    }

    result = tools.get_mailtips.fn(emails=["alice@example.com", "bob@example.com"])

    assert len(result) == 2
    assert result[0]["email"] == "alice@example.com"
    assert result[1]["email"] == "bob@example.com"
    assert result[1]["mailbox_full"] is True


@patch("src.microsoft_mcp.tools.graph")
def test_get_mailtips_missing_fields_default_gracefully(mock_graph):
    from src.microsoft_mcp import tools

    # Minimal tip — Graph may omit optional fields
    minimal_tip = {
        "emailAddress": {"address": "sparse@example.com"},
        "automaticReplies": {},
    }
    mock_graph.request.return_value = {"value": [minimal_tip]}

    result = tools.get_mailtips.fn(emails=["sparse@example.com"])

    tip = result[0]
    assert tip["email"] == "sparse@example.com"
    assert tip["auto_reply"] is None
    assert tip["mailbox_full"] is False
    assert tip["max_message_size_bytes"] is None
    assert tip["recipient_scope"] is None
    assert tip["delivery_restricted"] is False


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


@patch("src.microsoft_mcp.tools.graph")
def test_get_mailtips_raises_on_empty_emails(mock_graph):
    from src.microsoft_mcp import tools

    with pytest.raises(ValueError, match="emails"):
        tools.get_mailtips.fn(emails=[])

    mock_graph.request.assert_not_called()


# ---------------------------------------------------------------------------
# Error propagation
# ---------------------------------------------------------------------------


@patch("src.microsoft_mcp.tools.graph")
def test_get_mailtips_reraises_on_graph_error(mock_graph):
    from src.microsoft_mcp import tools

    mock_graph.request.side_effect = RuntimeError("Graph 503")

    with pytest.raises(RuntimeError, match="Graph 503"):
        tools.get_mailtips.fn(emails=["alice@example.com"])
