# Generated by OrchestKit Claude Plugin
# Created: 2026-06-16

from src.microsoft_mcp import rules


# ---------------------------------------------------------------------------
# template_to_rule_payload
# ---------------------------------------------------------------------------


def test_template_to_rule_payload_resolves_folder():
    tpl = {
        "name": "N",
        "sequence": 5,
        "conditions": {"sender_contains": ["x.com"]},
        "actions": {"move_to": "News", "mark_as_read": True, "stop_processing": True},
    }
    p = rules.template_to_rule_payload(tpl, folder_resolver=lambda n: f"ID::{n}")
    assert p["displayName"] == "N" and p["sequence"] == 5
    assert p["conditions"]["senderContains"] == ["x.com"]
    assert p["actions"]["moveToFolder"] == "ID::News"
    assert p["actions"]["markAsRead"] is True
    assert p["actions"]["stopProcessingRules"] is True


def test_template_to_rule_payload_no_resolver_passes_name_through():
    tpl = {
        "name": "Test",
        "conditions": {"subject_contains": ["invoice"]},
        "actions": {"move_to": "Invoices"},
    }
    p = rules.template_to_rule_payload(tpl)
    assert p["actions"]["moveToFolder"] == "Invoices"


def test_template_to_rule_payload_all_conditions():
    tpl = {
        "name": "AllConds",
        "conditions": {
            "sender_contains": ["a.com"],
            "subject_contains": ["hello"],
            "body_contains": ["world"],
            "from_addresses": ["user@a.com"],
            "has_attachments": True,
            "importance": "high",
        },
        "actions": {"mark_as_read": True},
    }
    p = rules.template_to_rule_payload(tpl)
    conds = p["conditions"]
    assert conds["senderContains"] == ["a.com"]
    assert conds["subjectContains"] == ["hello"]
    assert conds["bodyContains"] == ["world"]
    assert conds["fromAddresses"] == [{"emailAddress": {"address": "user@a.com"}}]
    assert conds["hasAttachments"] is True
    assert conds["importance"] == "high"


def test_template_to_rule_payload_all_actions():
    tpl = {
        "name": "AllActs",
        "conditions": {"sender_contains": ["b.com"]},
        "actions": {
            "copy_to": "Archive",
            "assign_categories": ["Cat1", "Cat2"],
            "mark_importance": "low",
            "forward_to": ["fwd@example.com"],
            "delete": True,
            "stop_processing": True,
        },
    }
    p = rules.template_to_rule_payload(tpl, folder_resolver=lambda n: f"FID::{n}")
    acts = p["actions"]
    assert acts["copyToFolder"] == "FID::Archive"
    assert acts["assignCategories"] == ["Cat1", "Cat2"]
    assert acts["markImportance"] == "low"
    assert acts["forwardTo"] == [{"emailAddress": {"address": "fwd@example.com"}}]
    assert acts["delete"] is True
    assert acts["stopProcessingRules"] is True


def test_template_to_rule_payload_enabled_default_true():
    tpl = {
        "name": "En",
        "conditions": {"sender_contains": ["c.com"]},
        "actions": {"mark_as_read": True},
    }
    p = rules.template_to_rule_payload(tpl)
    assert p["isEnabled"] is True


def test_template_to_rule_payload_enabled_false():
    tpl = {
        "name": "Dis",
        "enabled": False,
        "conditions": {"sender_contains": ["c.com"]},
        "actions": {"mark_as_read": True},
    }
    p = rules.template_to_rule_payload(tpl)
    assert p["isEnabled"] is False


# ---------------------------------------------------------------------------
# validate_template
# ---------------------------------------------------------------------------


def test_validate_template_requires_condition_and_action():
    assert rules.validate_template({"name": "x"}) != []
    assert (
        rules.validate_template(
            {
                "name": "x",
                "conditions": {"sender_contains": ["a"]},
                "actions": {"mark_as_read": True},
            }
        )
        == []
    )


def test_validate_template_missing_name():
    errs = rules.validate_template(
        {"conditions": {"sender_contains": ["a"]}, "actions": {"mark_as_read": True}}
    )
    assert any("name" in e.lower() for e in errs)


def test_validate_template_no_conditions():
    errs = rules.validate_template(
        {"name": "x", "conditions": {}, "actions": {"mark_as_read": True}}
    )
    assert any("condition" in e.lower() for e in errs)


def test_validate_template_stop_processing_counts_as_action():
    errs = rules.validate_template(
        {
            "name": "x",
            "conditions": {"sender_contains": ["a"]},
            "actions": {"stop_processing": True},
        }
    )
    assert errs == []


def test_validate_template_enabled_must_be_bool():
    errs = rules.validate_template(
        {
            "name": "x",
            "enabled": "yes",
            "conditions": {"sender_contains": ["a"]},
            "actions": {"mark_as_read": True},
        }
    )
    assert any("enabled" in e.lower() for e in errs)


def test_validate_template_sequence_must_be_int():
    errs = rules.validate_template(
        {
            "name": "x",
            "sequence": "five",
            "conditions": {"sender_contains": ["a"]},
            "actions": {"mark_as_read": True},
        }
    )
    assert any("sequence" in e.lower() for e in errs)


def test_validate_template_importance_valid_values():
    for val in ("low", "normal", "high", "Low", "HIGH"):
        errs = rules.validate_template(
            {
                "name": "x",
                "conditions": {"importance": val},
                "actions": {"mark_as_read": True},
            }
        )
        assert errs == [], f"Expected valid for importance={val!r}, got {errs}"


def test_validate_template_importance_invalid():
    errs = rules.validate_template(
        {
            "name": "x",
            "conditions": {"importance": "critical"},
            "actions": {"mark_as_read": True},
        }
    )
    assert any("importance" in e.lower() for e in errs)


def test_validate_template_mark_importance_in_actions():
    errs = rules.validate_template(
        {
            "name": "x",
            "conditions": {"sender_contains": ["a"]},
            "actions": {"mark_importance": "urgent"},
        }
    )
    assert any("importance" in e.lower() for e in errs)


# ---------------------------------------------------------------------------
# rule_to_template
# ---------------------------------------------------------------------------


def test_rule_to_template_basic():
    rule = {
        "displayName": "My Rule",
        "sequence": 3,
        "isEnabled": True,
        "conditions": {
            "senderContains": ["acme.com"],
            "subjectContains": ["invoice"],
        },
        "actions": {
            "moveToFolder": "FolderID123",
            "markAsRead": True,
        },
    }
    tpl = rules.rule_to_template(rule)
    assert tpl["name"] == "My Rule"
    assert tpl["sequence"] == 3
    assert tpl["enabled"] is True
    assert tpl["conditions"]["sender_contains"] == ["acme.com"]
    assert tpl["conditions"]["subject_contains"] == ["invoice"]
    assert tpl["actions"]["move_to"] == "FolderID123"
    assert tpl["actions"]["mark_as_read"] is True


def test_rule_to_template_with_folder_namer():
    rule = {
        "displayName": "Named",
        "isEnabled": True,
        "conditions": {"senderContains": ["x.com"]},
        "actions": {"moveToFolder": "ID::Newsletters", "copyToFolder": "ID::Archive"},
    }
    tpl = rules.rule_to_template(rule, folder_namer=lambda fid: fid.replace("ID::", ""))
    assert tpl["actions"]["move_to"] == "Newsletters"
    assert tpl["actions"]["copy_to"] == "Archive"


def test_rule_to_template_all_conditions():
    rule = {
        "displayName": "R",
        "isEnabled": False,
        "conditions": {
            "senderContains": ["s.com"],
            "subjectContains": ["sub"],
            "bodyContains": ["bdy"],
            "fromAddresses": [{"emailAddress": {"address": "u@a.com"}}],
            "hasAttachments": True,
            "importance": "low",
        },
        "actions": {"markAsRead": True},
    }
    tpl = rules.rule_to_template(rule)
    conds = tpl["conditions"]
    assert conds["sender_contains"] == ["s.com"]
    assert conds["subject_contains"] == ["sub"]
    assert conds["body_contains"] == ["bdy"]
    assert conds["from_addresses"] == ["u@a.com"]
    assert conds["has_attachments"] is True
    assert conds["importance"] == "low"


def test_rule_to_template_all_actions():
    rule = {
        "displayName": "R2",
        "isEnabled": True,
        "conditions": {"senderContains": ["z.com"]},
        "actions": {
            "moveToFolder": "FID1",
            "copyToFolder": "FID2",
            "assignCategories": ["A", "B"],
            "markImportance": "high",
            "forwardTo": [{"emailAddress": {"address": "fwd@x.com"}}],
            "delete": True,
            "stopProcessingRules": True,
        },
    }
    tpl = rules.rule_to_template(rule)
    acts = tpl["actions"]
    assert acts["move_to"] == "FID1"
    assert acts["copy_to"] == "FID2"
    assert acts["assign_categories"] == ["A", "B"]
    assert acts["mark_importance"] == "high"
    assert acts["forward_to"] == ["fwd@x.com"]
    assert acts["delete"] is True
    assert acts["stop_processing"] is True


# ---------------------------------------------------------------------------
# Round-trip: rule_to_template(template_to_rule_payload(tpl)) semantics
# ---------------------------------------------------------------------------


def test_round_trip_preserves_semantics():
    tpl = {
        "name": "RT Test",
        "enabled": True,
        "sequence": 7,
        "conditions": {
            "sender_contains": ["round.com"],
            "subject_contains": ["trip"],
        },
        "actions": {
            "move_to": "Trips",
            "mark_as_read": True,
            "assign_categories": ["Travel"],
            "stop_processing": True,
        },
    }
    payload = rules.template_to_rule_payload(tpl)
    # Inject an id so rule_to_template gets a realistic rule dict
    payload["id"] = "fake-id"
    payload["displayName"] = payload["displayName"]  # already set

    recovered = rules.rule_to_template(payload)

    assert recovered["name"] == tpl["name"]
    assert recovered["enabled"] == tpl["enabled"]
    assert recovered["sequence"] == tpl["sequence"]
    assert (
        recovered["conditions"]["sender_contains"]
        == tpl["conditions"]["sender_contains"]
    )
    assert (
        recovered["conditions"]["subject_contains"]
        == tpl["conditions"]["subject_contains"]
    )
    assert recovered["actions"]["move_to"] == tpl["actions"]["move_to"]
    assert recovered["actions"]["mark_as_read"] == tpl["actions"]["mark_as_read"]
    assert (
        recovered["actions"]["assign_categories"] == tpl["actions"]["assign_categories"]
    )
    assert recovered["actions"]["stop_processing"] == tpl["actions"]["stop_processing"]
