# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Tests for template MCP tools + create_email_draft template integration."""

from __future__ import annotations

from unittest.mock import patch


# ---------------------------------------------------------------------------
# list_email_templates
# ---------------------------------------------------------------------------


def test_list_email_templates_returns_bundled():
    from microsoft_mcp.tools import list_email_templates

    templates = list_email_templates.fn()
    names = [(t["category"], t["name"]) for t in templates]
    # Bundled templates must include these
    assert ("calendar", "meeting") in names
    assert ("calendar", "interview") in names
    assert ("email", "followup") in names


def test_list_email_templates_category_filter():
    from microsoft_mcp.tools import list_email_templates

    calendar = list_email_templates.fn(category="calendar")
    assert all(t["category"] == "calendar" for t in calendar)
    assert any(t["name"] == "meeting" for t in calendar)

    email = list_email_templates.fn(category="email")
    assert all(t["category"] == "email" for t in email)
    assert any(t["name"] == "followup" for t in email)


def test_list_email_templates_fields():
    from microsoft_mcp.tools import list_email_templates

    templates = list_email_templates.fn()
    for t in templates:
        assert "name" in t
        assert "category" in t
        assert "description" in t
        assert "placeholders" in t


# ---------------------------------------------------------------------------
# get_template_placeholders
# ---------------------------------------------------------------------------


def test_get_template_placeholders_meeting():
    from microsoft_mcp.tools import get_template_placeholders

    placeholders = get_template_placeholders.fn(category="calendar", name="meeting")
    names = [p["name"] for p in placeholders]
    assert "subject" in names
    assert "agenda" in names


def test_get_template_placeholders_subject_required():
    from microsoft_mcp.tools import get_template_placeholders

    placeholders = get_template_placeholders.fn(category="calendar", name="meeting")
    subject_ph = next(p for p in placeholders if p["name"] == "subject")
    assert subject_ph.get("required") is True


def test_get_template_placeholders_not_found():
    from microsoft_mcp.tools import get_template_placeholders
    import pytest

    with pytest.raises(ValueError):
        get_template_placeholders.fn(category="email", name="nonexistent_xyz")


# ---------------------------------------------------------------------------
# render_email_template
# ---------------------------------------------------------------------------


def test_render_email_template_followup():
    from microsoft_mcp.tools import render_email_template

    result = render_email_template.fn(
        category="email",
        name="followup",
        data={
            "recipient_name": "Alice",
            "sender_name": "Bob",
            "context": "our call yesterday",
        },
    )
    assert "Alice" in result
    assert "Bob" in result
    assert "our call yesterday" in result


def test_render_email_template_missing_required_raises():
    from microsoft_mcp.tools import render_email_template
    import pytest

    with pytest.raises(ValueError, match="required"):
        render_email_template.fn(
            category="email",
            name="followup",
            data={},
        )


def test_render_email_template_meeting_with_agenda():
    from microsoft_mcp.tools import render_email_template

    result = render_email_template.fn(
        category="calendar",
        name="meeting",
        data={
            "subject": "Sprint Review",
            "agenda": "Demo,Retro,Planning",
        },
    )
    assert "Sprint Review" in result
    # agenda items rendered as list rows
    assert "Demo" in result
    assert "Retro" in result
    assert "Planning" in result
    # numbered list HTML
    assert "<tr><td>1." in result
    assert "<tr><td>2." in result


def test_render_email_template_not_found():
    from microsoft_mcp.tools import render_email_template
    import pytest

    with pytest.raises(ValueError):
        render_email_template.fn(category="email", name="no_such_template", data={})


# ---------------------------------------------------------------------------
# find_template_variables
# ---------------------------------------------------------------------------


def test_find_template_variables_basic():
    from microsoft_mcp.tools import find_template_variables

    result = find_template_variables.fn("Hello {{first_name}}, your code is {{code}}.")
    assert result == ["first_name", "code"]


def test_find_template_variables_empty():
    from microsoft_mcp.tools import find_template_variables

    assert find_template_variables.fn("No variables here.") == []


def test_find_template_variables_deduplicates():
    from microsoft_mcp.tools import find_template_variables

    result = find_template_variables.fn("{{a}} and {{b}} and {{a}}")
    assert result == ["a", "b"]


# ---------------------------------------------------------------------------
# substitute_template_variables
# ---------------------------------------------------------------------------


def test_substitute_template_variables_basic():
    from microsoft_mcp.tools import substitute_template_variables

    result = substitute_template_variables.fn(
        content="Hello {{name}}!",
        values={"name": "World"},
    )
    assert result == "Hello World!"


def test_substitute_template_variables_missing_lenient():
    from microsoft_mcp.tools import substitute_template_variables

    result = substitute_template_variables.fn(
        content="Hi {{name}} and {{other}}",
        values={"name": "Sam"},
        strict=False,
    )
    assert "Sam" in result
    assert "{{other}}" in result


def test_substitute_template_variables_strict_raises():
    from microsoft_mcp.tools import substitute_template_variables
    import pytest

    with pytest.raises(ValueError, match="other"):
        substitute_template_variables.fn(
            content="Hi {{name}} and {{other}}",
            values={"name": "Sam"},
            strict=True,
        )


# ---------------------------------------------------------------------------
# create_email_draft with template integration
# ---------------------------------------------------------------------------


def _draft_message(draft_id: str, **overrides):
    draft = {
        "id": draft_id,
        "subject": "Draft subject",
        "from": {"emailAddress": {"name": "Me", "address": "me@example.com"}},
        "toRecipients": [{"emailAddress": {"address": "alice@example.com"}}],
        "ccRecipients": [],
        "bccRecipients": [],
        "body": {"contentType": "html", "content": "<p>body</p>"},
        "bodyPreview": "body",
        "conversationId": f"conv-{draft_id}",
        "webLink": f"https://outlook.office.com/mail/deeplink/compose/{draft_id}",
        "createdDateTime": "2026-04-02T10:00:00Z",
        "lastModifiedDateTime": "2026-04-02T10:01:00Z",
        "isDraft": True,
        "isRead": True,
    }
    draft.update(overrides)
    return draft


@patch("microsoft_mcp.tools.graph")
def test_create_email_draft_with_template(mock_graph, monkeypatch):
    """Rendering email/followup via template= produces correct HTML body in POST payload."""
    monkeypatch.setenv("MICROSOFT_MCP_DEFAULT_SIGNATURE", "")
    monkeypatch.setenv("MICROSOFT_MCP_REPLY_SIGNATURE", "")
    monkeypatch.setenv("MICROSOFT_MCP_SIGNATURES_DIR", "")

    from microsoft_mcp.tools import create_email_draft

    mock_graph.request.return_value = _draft_message("d-tpl-1")

    result = create_email_draft.fn(
        draft_type="new",
        to_recipients=["alice@example.com"],
        subject="Follow up",
        template="email/followup",
        template_data={
            "recipient_name": "Alice",
            "sender_name": "Bob",
            "context": "our demo call",
        },
    )

    assert result["status"] == "draft_created"
    assert result["draft_id"] == "d-tpl-1"

    # Verify the POST body payload contains rendered HTML
    call_args = mock_graph.request.call_args
    assert call_args[0][0] == "POST"
    assert call_args[0][1] == "/me/messages"
    posted_body = call_args[1]["json"]["body"]
    assert posted_body["contentType"] == "html"
    assert "Alice" in posted_body["content"]
    assert "Bob" in posted_body["content"]
    assert "our demo call" in posted_body["content"]


@patch("microsoft_mcp.tools.graph")
def test_create_email_draft_template_overrides_body(mock_graph, monkeypatch):
    """When template= is supplied, explicit body= is ignored."""
    monkeypatch.setenv("MICROSOFT_MCP_DEFAULT_SIGNATURE", "")
    monkeypatch.setenv("MICROSOFT_MCP_REPLY_SIGNATURE", "")
    monkeypatch.setenv("MICROSOFT_MCP_SIGNATURES_DIR", "")

    from microsoft_mcp.tools import create_email_draft

    mock_graph.request.return_value = _draft_message("d-tpl-2")

    create_email_draft.fn(
        draft_type="new",
        to_recipients=["alice@example.com"],
        body="THIS SHOULD BE IGNORED",
        template="email/followup",
        template_data={
            "recipient_name": "Carol",
            "sender_name": "Dave",
            "context": "our last meeting",
        },
    )

    call_args = mock_graph.request.call_args
    posted_content = call_args[1]["json"]["body"]["content"]
    assert "THIS SHOULD BE IGNORED" not in posted_content
    assert "Carol" in posted_content


@patch("microsoft_mcp.tools.graph")
def test_create_email_draft_no_template_unchanged(mock_graph, monkeypatch):
    """Without template=, existing behavior is preserved."""
    monkeypatch.setenv("MICROSOFT_MCP_DEFAULT_SIGNATURE", "")
    monkeypatch.setenv("MICROSOFT_MCP_REPLY_SIGNATURE", "")
    monkeypatch.setenv("MICROSOFT_MCP_SIGNATURES_DIR", "")

    from microsoft_mcp.tools import create_email_draft

    mock_graph.request.return_value = _draft_message("d-no-tpl")

    create_email_draft.fn(
        draft_type="new",
        to_recipients=["alice@example.com"],
        body="Plain body text",
        body_content_type="text",
    )

    call_args = mock_graph.request.call_args
    posted = call_args[1]["json"]["body"]
    assert posted["contentType"] == "text"
    assert posted["content"] == "Plain body text"


def test_create_email_draft_invalid_template_format(monkeypatch):
    """Malformed template= raises ValueError before any Graph call."""
    monkeypatch.setenv("MICROSOFT_MCP_DEFAULT_SIGNATURE", "")
    monkeypatch.setenv("MICROSOFT_MCP_REPLY_SIGNATURE", "")
    monkeypatch.setenv("MICROSOFT_MCP_SIGNATURES_DIR", "")

    from microsoft_mcp.tools import create_email_draft
    import pytest

    with pytest.raises(ValueError, match="category/name"):
        create_email_draft.fn(
            draft_type="new",
            to_recipients=["alice@example.com"],
            template="bad-format-no-slash",
        )


# ---------------------------------------------------------------------------
# List-rendering regression: calendar/meeting agenda produces <tr> rows
# ---------------------------------------------------------------------------


def test_meeting_template_agenda_list_rendering():
    """Closing a 7.1 gap: comma-separated agenda renders numbered <tr> rows."""
    from microsoft_mcp.tools import render_email_template

    result = render_email_template.fn(
        category="calendar",
        name="meeting",
        data={
            "subject": "All Hands",
            "agenda": "Intro,Updates,Q&amp;A",
        },
    )
    # Each agenda item gets a numbered table row
    assert "<tr><td>1." in result
    assert "<tr><td>2." in result
    assert "<tr><td>3." in result
    assert "Intro" in result
    assert "Updates" in result


def test_interview_template_interviewers_list_rendering():
    """interview/calendar: interviewers comma-list renders bullet <tr> rows."""
    from microsoft_mcp.tools import render_email_template

    result = render_email_template.fn(
        category="calendar",
        name="interview",
        data={
            "subject": "SWE Interview - Jane Doe",
            "interviewers": "Alice Smith,Bob Jones",
        },
    )
    assert "Alice Smith" in result
    assert "Bob Jones" in result
    # Bullet rows (not numbered)
    assert "<tr><td>•" in result
