# Generated by OrchestKit Claude Plugin
# Created: 2026-06-16

"""CLI for refreshing, verifying, and inspecting MSAL tokens.

Exposed two ways (mirrors signatures_cli.py):
- ``microsoft-mcp-auth <cmd> ...``   (standalone console script)
- ``microsoft-mcp auth <cmd> ...``   (subcommand of the main entry point)

Both routes share ``main()``. Only the MSAL auth method is supported; the
Azure SDK path manages its own token cache.
"""

from __future__ import annotations

import datetime as dt
import os
import sys
from typing import Any

# ---------------------------------------------------------------------------
# ANSI color (zero-dependency, TTY-gated, honors NO_COLOR)

_RESET = "\033[0m"
_COLORS = {
    "green": "\033[32m",
    "red": "\033[31m",
    "yellow": "\033[33m",
    "dim": "\033[2m",
}


def _color_enabled(stream: Any = None) -> bool:
    stream = stream if stream is not None else sys.stdout
    if os.environ.get("NO_COLOR") is not None:
        return False
    if os.environ.get("MICROSOFT_MCP_FORCE_COLOR") == "1":
        return True
    if os.environ.get("TERM", "") == "dumb":
        return False
    isatty = getattr(stream, "isatty", None)
    return bool(isatty()) if callable(isatty) else False


def _c(text: str, color: str) -> str:
    if not _color_enabled():
        return text
    return f"{_COLORS.get(color, '')}{text}{_RESET}"


# ---------------------------------------------------------------------------
# Formatting


def _format_expiry(expires_at: str | None) -> str:
    """Convert stored '%Y-%m-%dT%H:%M:%SZ' to '%Y-%m-%d %H:%M:%S UTC'."""
    if not expires_at:
        return "unknown"
    raw = expires_at.replace("Z", "+00:00")
    try:
        parsed = dt.datetime.fromisoformat(raw)
    except ValueError:
        return expires_at
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=dt.timezone.utc)
    return parsed.astimezone(dt.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
