# Generated by OrchestKit Claude Plugin
# Created: 2026-06-16

"""Pure, Graph-free helpers for Outlook inbox message rules.

All network I/O lives in tools.py; this module only builds payloads,
summarizes rules for display, and converts to/from YAML templates.
"""

from __future__ import annotations

from typing import Any

RULE_LIST_FIELDS = "id,displayName,sequence,isEnabled,conditions,actions"
RULE_DETAIL_FIELDS = (
    "id,displayName,sequence,isEnabled,hasError,isReadOnly,"
    "conditions,actions,exceptions"
)

# Human-readable labels for the boolean/scalar predicate keys.
_CONDITION_LABELS: dict[str, str] = {
    "hasAttachments": "has attachments",
    "isApprovalRequest": "is approval request",
    "isAutomaticForward": "is auto-forward",
    "isAutomaticReply": "is auto-reply",
    "isEncrypted": "is encrypted",
    "isMeetingRequest": "is meeting request",
    "isMeetingResponse": "is meeting response",
    "isNonDeliveryReport": "is NDR/bounce",
    "isPermissionControlled": "is permission-controlled",
    "isReadReceipt": "is read receipt",
    "isSigned": "is signed",
    "isVoicemail": "is voicemail",
    "sentToMe": "sent to me",
    "sentCcMe": "cc's me",
    "sentOnlyToMe": "sent only to me",
    "sentToOrCcMe": "sent to or cc's me",
    "notSentToMe": "not sent to me",
}
_LIST_CONDITION_LABELS: dict[str, str] = {
    "bodyContains": "body contains",
    "bodyOrSubjectContains": "body/subject contains",
    "headerContains": "header contains",
    "subjectContains": "subject contains",
    "senderContains": "sender contains",
    "recipientContains": "recipient contains",
    "categories": "categorized",
}


def _addrs(recips: list[dict[str, Any]]) -> list[str]:
    out = []
    for r in recips or []:
        ea = r.get("emailAddress", {}) if isinstance(r, dict) else {}
        out.append(ea.get("address") or ea.get("name") or "")
    return [a for a in out if a]


def summarize_conditions(conditions: dict[str, Any] | None) -> str:
    if not conditions:
        return "(any message)"
    parts: list[str] = []
    for key, label in _LIST_CONDITION_LABELS.items():
        vals = conditions.get(key)
        if vals:
            parts.append(f"{label} {', '.join(vals)}")
    if conditions.get("fromAddresses"):
        parts.append(f"from {', '.join(_addrs(conditions['fromAddresses']))}")
    if conditions.get("sentToAddresses"):
        parts.append(f"sent to {', '.join(_addrs(conditions['sentToAddresses']))}")
    if conditions.get("importance"):
        parts.append(f"importance={conditions['importance']}")
    for key, label in _CONDITION_LABELS.items():
        if conditions.get(key):
            parts.append(label)
    return "; ".join(parts) if parts else "(any message)"


def summarize_actions(actions: dict[str, Any] | None) -> str:
    if not actions:
        return "(no actions)"
    parts: list[str] = []
    if actions.get("moveToFolder"):
        parts.append(f"move to {actions['moveToFolder']}")
    if actions.get("copyToFolder"):
        parts.append(f"copy to {actions['copyToFolder']}")
    if actions.get("assignCategories"):
        parts.append(f"categorize {', '.join(actions['assignCategories'])}")
    if actions.get("markImportance"):
        parts.append(f"mark importance {actions['markImportance']}")
    if actions.get("markAsRead"):
        parts.append("mark as read")
    if actions.get("forwardTo"):
        parts.append(f"forward to {', '.join(_addrs(actions['forwardTo']))}")
    if actions.get("redirectTo"):
        parts.append(f"redirect to {', '.join(_addrs(actions['redirectTo']))}")
    if actions.get("delete"):
        parts.append("delete")
    if actions.get("permanentDelete"):
        parts.append("permanently delete")
    if actions.get("stopProcessingRules"):
        parts.append("stop processing further rules")
    return "; ".join(parts) if parts else "(no actions)"


def shape_rule_summary(rule: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": rule.get("id"),
        "display_name": rule.get("displayName"),
        "sequence": rule.get("sequence"),
        "is_enabled": rule.get("isEnabled"),
        "conditions_summary": summarize_conditions(rule.get("conditions")),
        "actions_summary": summarize_actions(rule.get("actions")),
    }
